FROM node:16-alpine3.12 as build
WORKDIR /app/
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
EXPOSE 3000

FROM nginx:1.21.3
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80