FROM node:16-alpine3.12

RUN mkdir -p /app/cache
WORKDIR /app/cache
COPY package.json .
RUN npm install

WORKDIR /app/
# COPY package.json .
# RUN npm install
ENV NODE_PATH=/app/node_modules/.bin
COPY . .
EXPOSE 3000

ENTRYPOINT ["/bin/sh", "entrypoint.sh"]
# ENTRYPOINT ["npm", "start"]